# Generated by Django 5.0.2 on 2024-03-02 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_post_blogpost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("title",)},
        ),
    ]
