# Generated by Django 5.0.2 on 2024-03-02 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blogpost_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ("-created_at",)},
        ),
    ]
