# Generated by Django 5.0.2 on 2024-03-12 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_userpostfav"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userpostfav",
            old_name="is_active",
            new_name="is_deleted",
        ),
    ]
