# Generated by Django 5.0.2 on 2024-02-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0003_alter_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
